name: Show Dependencies

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  show-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Repository herunterladen
        uses: actions/checkout@v4

      - name: Node.js installieren
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Abhängigkeitsbaum anzeigen
        run: npm ls
